export const themes = [
    "Taylor Swift",
    "Friends",
    "Selena Gomez",
    "Ariana Grande",
    "Barbie",
    "Stranger Things",
    "The Crown",
    "Gilmore Girls",
    "The Princess Diaries",
    "Emily in Paris",
    "Bridgerton",
    "Grease",
    "Mean Girls",
    "The Devil Wears Prada",
    "Sex and the City",
    "Pretty Little Liars",
    "Gossip Girl",
    "Legally Blonde",
    "Hannah Montana",
    "High School Musical",
    "Frozen",
    "Wonder Woman",
    "Cinderella",
    "Beauty and the Beast",
    "Moana",
    "Maleficent",
    "The Hunger Games",
    "Twilight",
    "Lizzo",
    "Beyoncé",
    "Rihanna",
    "Jennifer Lopez",
    "Billie Eilish",
    "Lady Gaga",
    "Zendaya",
    "Blackpink",
    "The Kardashians",
    "Euphoria",
    "Riverdale",
    "RuPaul's Drag Race",
    "America's Next Top Model",
    "The Bold Type"
];
